# Generated by Django 4.0.2 on 2022-04-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128, null=True)),
                ('street', models.CharField(max_length=128, null=True)),
                ('distinct', models.CharField(max_length=128, null=True)),
                ('city', models.CharField(max_length=128, null=True)),
                ('description', models.CharField(max_length=1024)),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
