# Generated by Django 4.0.2 on 2022-05-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_information_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(to='ecommerce.CartItem'),
        ),
    ]
