# Generated by Django 4.0.2 on 2022-05-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_order_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.shipmentunit'),
            preserve_default=False,
        ),
    ]
