# Generated by Django 4.0.2 on 2022-04-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_bankinfo_cart_shipment_shipmentunit_payment_order_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bankinfo',
            table='ecommerce_bank_info',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='ecommerce_cart_item',
        ),
        migrations.AlterModelTable(
            name='shipmentunit',
            table='ecommerce_shipment_unit',
        ),
    ]
