# Generated by Django 4.0.2 on 2022-05-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_shipment_shipment_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
